### PR TITLE
Confluent for Kubernetes

### PR DESCRIPTION
**Pull request by d4kine**
Thought I added my Kafka/Schema-Registry with Confluent to the k3d installation :)

### CODE REVIEW

**Comment by FabianHardt** [comment]
Hi @d4kine,
are you still working on this features?
Or maybe we should close this PR after about 2 years? :)
Many greetings

**Comment by d4kine** [comment]
Hey @FabianHardt,
seems like I postponed this one for quite a year :D
My last status was, that it worked in general but was very resource consuming.
I'll check on it the next few days and keep you updated.
Cheers

**Comment by d4kine** [comment]
Ready to merge 😉

**Review by FabianHardt — APPROVED** [review]
Looks really great!

**Comment by FabianHardt** [comment]
Thanks for your work :)

**Pull request merged**
